services:
  berries-service-1:
    build:
      context: .
      dockerfile: BerryService/Dockerfile
    ports:
      - "5101:80"
    networks:
      - greenmarket-network

  berries-service-2:
    build:
      context: .
      dockerfile: BerryService/Dockerfile
    ports:
      - "5102:80"
    networks:
      - greenmarket-network

  fruits-service-1:
    build:
      context: .
      dockerfile: FruitService/Dockerfile
    ports:
      - "5201:80"
    networks:
      - greenmarket-network

  fruits-service-2:
    build:
      context: .
      dockerfile: FruitService/Dockerfile
    ports:
      - "5202:80"
    networks:
      - greenmarket-network

  fruits-service-3:
    build:
      context: .
      dockerfile: FruitService/Dockerfile
    ports:
      - "5203:80"
    networks:
      - greenmarket-network

  vegetables-service:
    build:
      context: .
      dockerfile: VegetablesService/Dockerfile
    ports:
      - "5003:80"
    networks:
      - greenmarket-network

  nuts-service:
    build:
      context: .
      dockerfile: NutsService/Dockerfile
    ports:
      - "5004:80"
    networks:
      - greenmarket-network
        
  seeds-service:
    build:
      context: .
      dockerfile: SeedsService/Dockerfile
    ports:
      - "5005:80"
    networks:
      - greenmarket-network

  gateway-service:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "5000:8080"
    environment:  
      - ASPNETCORE_ENVIRONMENT=Docker  
    depends_on:
      - berries-service-1
      - berries-service-2
      - fruits-service-1
      - fruits-service-2
      - fruits-service-3
      - vegetables-service
      - nuts-service
      - seeds-service
    networks:
      - greenmarket-network
        
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5000
    depends_on:
      - gateway-service
    networks:
      - greenmarket-network

networks:
  greenmarket-network:
    driver: bridge

volumes:
  node_modules: